name: Test Analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NODE JS
        uses: actions/setup-node@v3
        with:
          node-version: "23.5.0"

      - name: Install project
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"
          cache: "pip"

      - name: Install slither
        run: pip3 install -r requirements.txt

      - name: Show slither version
        run: slither .
