name: Test Analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'
        cache: 'pip'

    - name: Install slither
      run: pip3 install -r requirements.txt

    - name: Show slither version
      run: slither .